name: testing Memory Usage monitoring

on:
  workflow_dispatch:

jobs:
  test_monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Google Test
        uses: actions/checkout@v4.1.0
        with:
          repository: Adobe-HZ-POC/googletest
          path: testing-githubapps/test-repo
          ref: master
          token: ${{ secrets.ADMIN_TOKEN }}
