name: testing Memory Usage monitoring

on:
  workflow_dispatch:

jobs:
  test_monitor:
    runs-on: ubuntu-latest
    steps:
    - name: Memory Usage Monitoring
      run: echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
