name: testing Memory Usage monitoring

on:
  workflow_dispatch:

jobs:
  test_monitor:
    runs-on: [ self-hosted, ephemeral ]
    steps:
      - uses: actions/checkout@v4

      - name: Checkout other repo
        uses: actions/checkout@v4.1.0
        with:
          repository: testing-githubapps/test-repo
          path: test123/hello
          ref: master
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: look at path
        run: ls -la

        
      - name: look at second repo
        run: ls -la test123

      - name: look at second repo
        run: ls -la test123/hello

      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-docker-action@main
        with:
          who-to-greet: "ephemeral-runner"
